name: Deploy Demos to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: site

      - name: Checkout ruotong branch
        uses: actions/checkout@v4
        with:
          ref: ruotong
          path: site/ruotong

      - name: Checkout claire branch
        uses: actions/checkout@v4
        with:
          ref: claireoconnor612-patch-1
          path: site/claire

      - name: Checkout marjory branch
        uses: actions/checkout@v4
        with:
          ref: marjory-pineda
          path: site/marjory

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
